# 배포시 80포트 설정
server:
  port: 80
#server:
#  port: 8080

spring:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    host: localhost
    port: ${application.spring.redis.port}

  datasource:
    url: ${application.spring.datasource.url}
    username: ${application.spring.datasource.username}
    password: ${application.spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${application.spring.security.kakao.client-id}
            client-secret: ${application.spring.security.kakao.client-secret}
            redirect-uri: ${application.spring.security.kakao.redirect-uri}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id: ${application.spring.security.naver.client-id}
            client-secret: ${application.spring.security.naver.client-secret}
            redirect-uri: ${application.spring.security.naver.redirect-uri}
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

cloud:
  aws:
    region:
      static: ${aws.region.static}
    stack:
      auto: ${aws.stack.auto}

jwt:
  secret: ${application.jwt.secret}
  secret_refresh: ${application.jwt.secret_refresh}
