name: Develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 기본 체크아웃
    - name: Checkout
      uses: actions/checkout@v3
    # Gradlew 실행 허용
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew
    # JDK 11 세팅
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    # 환경 변수 설정
    - name: Set environment values
      run: |
        cd ./src/main/resources
        touch ./env.properties
        echo "${{ secrets.ENV_DEVELOP }}" > ./env.properties
      shell: bash
    # Gradle build (Test 제외)
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean build -x test
    # Docker build
    - name: Docker build
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker build -t atties_dev_spring .
        docker tag atties_dev_spring choo000407/atties_dev_spring:${GITHUB_SHA::7}
        docker push choo000407/atties_dev_spring:${GITHUB_SHA::7}
    # Deploy
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 43.200.100.183
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
          sudo docker pull choo000407/atties_dev_spring:${GITHUB_SHA::7}
          sudo docker tag choo000407/atties_dev_spring:${GITHUB_SHA::7} atties_dev_spring
          sudo docker-compose up -d
